_wandb:
    value:
        cli_version: 0.21.3
        e:
            csn4k0yy76z0yd5bowc93iiy38dj3pqo:
                args:
                    - --input_artifact
                    - preprocessed_data.csv:latest
                    - --artifact_root
                    - data
                    - --artifact_type
                    - segregated_data
                    - --test_size
                    - "0.3"
                    - --random_state
                    - "42"
                    - --stratify
                    - genre
                codePath: segregate/run.py
                codePathLocal: run.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1000240963584"
                        used: "689516486656"
                email: zcoulibalyeng@gmail.com
                executable: /opt/anaconda3/envs/mlflow-2b05c334639a6588d5c96ec48ecc7de59f6ca254/bin/python
                git:
                    commit: e5ea4966bc12634c785fe1e07322102e698f9ea0
                    remote: https://github.com/levisstrauss/genre_classification.git
                host: MacBookPro.lan
                memory:
                    total: "17179869184"
                os: macOS-26.2-x86_64-i386-64bit-Mach-O
                program: /Users/codemon/Desktop/genre_classification/segregate/run.py
                python: CPython 3.13.11
                root: /Users/codemon/Desktop/genre_classification/segregate
                startedAt: "2026-01-03T04:21:51.198444Z"
                writerId: csn4k0yy76z0yd5bowc93iiy38dj3pqo
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.11
            "5": 0.21.3
            "8":
                - 2
            "12": 0.21.3
            "13": darwin-x86_64
