_wandb:
    value:
        cli_version: 0.21.3
        e:
            vz6cz50gsrs57dj7lkv0k8o97i2xowrg:
                args:
                    - --file_url
                    - https://raw.githubusercontent.com/udacity/nd0821-c2-build-model-workflow-exercises/master/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/genres_mod.parquet
                    - --artifact_name
                    - raw_data.parquet
                    - --artifact_type
                    - raw_data
                    - --artifact_description
                    - Data as downloaded
                codePath: download/download_data.py
                codePathLocal: download_data.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1000240963584"
                        used: "689515597824"
                email: zcoulibalyeng@gmail.com
                executable: /opt/anaconda3/envs/mlflow-c8796fcdf2a60e9d2d7a0e2de87ce7cf78fe7920/bin/python
                git:
                    commit: e5ea4966bc12634c785fe1e07322102e698f9ea0
                    remote: https://github.com/levisstrauss/genre_classification.git
                host: MacBookPro.lan
                memory:
                    total: "17179869184"
                os: macOS-26.2-x86_64-i386-64bit-Mach-O
                program: /Users/codemon/Desktop/genre_classification/download/download_data.py
                python: CPython 3.13.11
                root: /Users/codemon/Desktop/genre_classification/download
                startedAt: "2026-01-03T04:21:11.044297Z"
                writerId: vz6cz50gsrs57dj7lkv0k8o97i2xowrg
        m: []
        python_version: 3.13.11
        t:
            "3":
                - 2
            "4": 3.13.11
            "5": 0.21.3
            "8":
                - 2
            "12": 0.21.3
            "13": darwin-x86_64
